/*
 * aida
 *
 * 1.0.722-rc.3+496a5e11f6297a76e2b83a2b26e743e21a1c18c1
 *
 * The version of the OpenAPI document: 1.0.722-rc.3+496a5e11f6297a76e2b83a2b26e743e21a1c18c1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Api;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing InkjetPrinterActionKind
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InkjetPrinterActionKindTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InkjetPrinterActionKind
        //private InkjetPrinterActionKind instance;

        public InkjetPrinterActionKindTests()
        {
            // TODO uncomment below to create an instance of InkjetPrinterActionKind
            //instance = new InkjetPrinterActionKind();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InkjetPrinterActionKind
        /// </summary>
        [Fact]
        public void InkjetPrinterActionKindInstanceTest()
        {
            // TODO uncomment below to test "IsType" InkjetPrinterActionKind
            //Assert.IsType<InkjetPrinterActionKind>(instance);
        }



    }

}
