/*
 * aida
 *
 * 1.0.691
 *
 * The version of the OpenAPI document: 1.0.691
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Api;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing OcrReadBackMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OcrReadBackMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OcrReadBackMessage
        //private OcrReadBackMessage instance;

        public OcrReadBackMessageTests()
        {
            // TODO uncomment below to create an instance of OcrReadBackMessage
            //instance = new OcrReadBackMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OcrReadBackMessage
        /// </summary>
        [Fact]
        public void OcrReadBackMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" OcrReadBackMessage
            //Assert.IsType<OcrReadBackMessage>(instance);
        }


        /// <summary>
        /// Test the property 'SourceJobInstanceId'
        /// </summary>
        [Fact]
        public void SourceJobInstanceIdTest()
        {
            // TODO unit test for the property 'SourceJobInstanceId'
        }
        /// <summary>
        /// Test the property 'MachineName'
        /// </summary>
        [Fact]
        public void MachineNameTest()
        {
            // TODO unit test for the property 'MachineName'
        }
        /// <summary>
        /// Test the property 'MachineSerial'
        /// </summary>
        [Fact]
        public void MachineSerialTest()
        {
            // TODO unit test for the property 'MachineSerial'
        }
        /// <summary>
        /// Test the property 'HostName'
        /// </summary>
        [Fact]
        public void HostNameTest()
        {
            // TODO unit test for the property 'HostName'
        }
        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
        /// <summary>
        /// Test the property 'BatchId'
        /// </summary>
        [Fact]
        public void BatchIdTest()
        {
            // TODO unit test for the property 'BatchId'
        }
        /// <summary>
        /// Test the property 'CorrelationId'
        /// </summary>
        [Fact]
        public void CorrelationIdTest()
        {
            // TODO unit test for the property 'CorrelationId'
        }
        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }
        /// <summary>
        /// Test the property 'WorkflowInstanceId'
        /// </summary>
        [Fact]
        public void WorkflowInstanceIdTest()
        {
            // TODO unit test for the property 'WorkflowInstanceId'
        }
        /// <summary>
        /// Test the property 'WorkflowInstanceName'
        /// </summary>
        [Fact]
        public void WorkflowInstanceNameTest()
        {
            // TODO unit test for the property 'WorkflowInstanceName'
        }
        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Fact]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }
        /// <summary>
        /// Test the property 'JobStatus'
        /// </summary>
        [Fact]
        public void JobStatusTest()
        {
            // TODO unit test for the property 'JobStatus'
        }
        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'AdditionalMetadata'
        /// </summary>
        [Fact]
        public void AdditionalMetadataTest()
        {
            // TODO unit test for the property 'AdditionalMetadata'
        }
        /// <summary>
        /// Test the property 'DocumentProduced'
        /// </summary>
        [Fact]
        public void DocumentProducedTest()
        {
            // TODO unit test for the property 'DocumentProduced'
        }
        /// <summary>
        /// Test the property 'DestructiveOperationExecuted'
        /// </summary>
        [Fact]
        public void DestructiveOperationExecutedTest()
        {
            // TODO unit test for the property 'DestructiveOperationExecuted'
        }
        /// <summary>
        /// Test the property 'Discriminator'
        /// </summary>
        [Fact]
        public void DiscriminatorTest()
        {
            // TODO unit test for the property 'Discriminator'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'MeanConfidence'
        /// </summary>
        [Fact]
        public void MeanConfidenceTest()
        {
            // TODO unit test for the property 'MeanConfidence'
        }

    }

}
