/*
 * aida
 *
 * 1.0.722-rc.3+496a5e11f6297a76e2b83a2b26e743e21a1c18c1
 *
 * The version of the OpenAPI document: 1.0.722-rc.3+496a5e11f6297a76e2b83a2b26e743e21a1c18c1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Api;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ReadHoldingRegistersRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReadHoldingRegistersRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReadHoldingRegistersRequest
        //private ReadHoldingRegistersRequest instance;

        public ReadHoldingRegistersRequestTests()
        {
            // TODO uncomment below to create an instance of ReadHoldingRegistersRequest
            //instance = new ReadHoldingRegistersRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReadHoldingRegistersRequest
        /// </summary>
        [Fact]
        public void ReadHoldingRegistersRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReadHoldingRegistersRequest
            //Assert.IsType<ReadHoldingRegistersRequest>(instance);
        }


        /// <summary>
        /// Test the property 'SlaveId'
        /// </summary>
        [Fact]
        public void SlaveIdTest()
        {
            // TODO unit test for the property 'SlaveId'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }

    }

}
