/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing BarcodeReadSettingsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BarcodeReadSettingsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BarcodeReadSettingsDto
        //private BarcodeReadSettingsDto instance;

        public BarcodeReadSettingsDtoTests()
        {
            // TODO uncomment below to create an instance of BarcodeReadSettingsDto
            //instance = new BarcodeReadSettingsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BarcodeReadSettingsDto
        /// </summary>
        [Fact]
        public void BarcodeReadSettingsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" BarcodeReadSettingsDto
            //Assert.IsType<BarcodeReadSettingsDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Roi'
        /// </summary>
        [Fact]
        public void RoiTest()
        {
            // TODO unit test for the property 'Roi'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'Angle'
        /// </summary>
        [Fact]
        public void AngleTest()
        {
            // TODO unit test for the property 'Angle'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ScannerId'
        /// </summary>
        [Fact]
        public void ScannerIdTest()
        {
            // TODO unit test for the property 'ScannerId'
        }
        /// <summary>
        /// Test the property 'CameraId'
        /// </summary>
        [Fact]
        public void CameraIdTest()
        {
            // TODO unit test for the property 'CameraId'
        }
        /// <summary>
        /// Test the property 'AcquisitionPresetName'
        /// </summary>
        [Fact]
        public void AcquisitionPresetNameTest()
        {
            // TODO unit test for the property 'AcquisitionPresetName'
        }
        /// <summary>
        /// Test the property 'CanBeDeleted'
        /// </summary>
        [Fact]
        public void CanBeDeletedTest()
        {
            // TODO unit test for the property 'CanBeDeleted'
        }

    }

}
