/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing CancelJobByCorrelationIdRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CancelJobByCorrelationIdRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CancelJobByCorrelationIdRequest
        //private CancelJobByCorrelationIdRequest instance;

        public CancelJobByCorrelationIdRequestTests()
        {
            // TODO uncomment below to create an instance of CancelJobByCorrelationIdRequest
            //instance = new CancelJobByCorrelationIdRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CancelJobByCorrelationIdRequest
        /// </summary>
        [Fact]
        public void CancelJobByCorrelationIdRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CancelJobByCorrelationIdRequest
            //Assert.IsType<CancelJobByCorrelationIdRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CorrelationIds'
        /// </summary>
        [Fact]
        public void CorrelationIdsTest()
        {
            // TODO unit test for the property 'CorrelationIds'
        }
        /// <summary>
        /// Test the property 'JobTemplateName'
        /// </summary>
        [Fact]
        public void JobTemplateNameTest()
        {
            // TODO unit test for the property 'JobTemplateName'
        }

    }

}
