/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing CartridgeHolderSlotDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartridgeHolderSlotDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartridgeHolderSlotDto
        //private CartridgeHolderSlotDto instance;

        public CartridgeHolderSlotDtoTests()
        {
            // TODO uncomment below to create an instance of CartridgeHolderSlotDto
            //instance = new CartridgeHolderSlotDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartridgeHolderSlotDto
        /// </summary>
        [Fact]
        public void CartridgeHolderSlotDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartridgeHolderSlotDto
            //Assert.IsType<CartridgeHolderSlotDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Cartridge'
        /// </summary>
        [Fact]
        public void CartridgeTest()
        {
            // TODO unit test for the property 'Cartridge'
        }
        /// <summary>
        /// Test the property 'SlotStatus'
        /// </summary>
        [Fact]
        public void SlotStatusTest()
        {
            // TODO unit test for the property 'SlotStatus'
        }
        /// <summary>
        /// Test the property 'FluidExpected'
        /// </summary>
        [Fact]
        public void FluidExpectedTest()
        {
            // TODO unit test for the property 'FluidExpected'
        }

    }

}
