/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing ColorDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ColorDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ColorDto
        //private ColorDto instance;

        public ColorDtoTests()
        {
            // TODO uncomment below to create an instance of ColorDto
            //instance = new ColorDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ColorDto
        /// </summary>
        [Fact]
        public void ColorDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ColorDto
            //Assert.IsType<ColorDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'HexValue'
        /// </summary>
        [Fact]
        public void HexValueTest()
        {
            // TODO unit test for the property 'HexValue'
        }

    }

}
