/*
 * aida-mini
 *
 * 1.0.522
 *
 * The version of the OpenAPI document: 1.0.522
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing CustomAttributeNamedArgument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomAttributeNamedArgumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomAttributeNamedArgument
        //private CustomAttributeNamedArgument instance;

        public CustomAttributeNamedArgumentTests()
        {
            // TODO uncomment below to create an instance of CustomAttributeNamedArgument
            //instance = new CustomAttributeNamedArgument();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomAttributeNamedArgument
        /// </summary>
        [Fact]
        public void CustomAttributeNamedArgumentInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomAttributeNamedArgument
            //Assert.IsType<CustomAttributeNamedArgument>(instance);
        }


        /// <summary>
        /// Test the property 'MemberInfo'
        /// </summary>
        [Fact]
        public void MemberInfoTest()
        {
            // TODO unit test for the property 'MemberInfo'
        }
        /// <summary>
        /// Test the property 'TypedValue'
        /// </summary>
        [Fact]
        public void TypedValueTest()
        {
            // TODO unit test for the property 'TypedValue'
        }
        /// <summary>
        /// Test the property 'MemberName'
        /// </summary>
        [Fact]
        public void MemberNameTest()
        {
            // TODO unit test for the property 'MemberName'
        }
        /// <summary>
        /// Test the property 'IsField'
        /// </summary>
        [Fact]
        public void IsFieldTest()
        {
            // TODO unit test for the property 'IsField'
        }

    }

}
