/*
 * aida-mini
 *
 * 1.0.522
 *
 * The version of the OpenAPI document: 1.0.522
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing CustomAttributeTypedArgument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomAttributeTypedArgumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomAttributeTypedArgument
        //private CustomAttributeTypedArgument instance;

        public CustomAttributeTypedArgumentTests()
        {
            // TODO uncomment below to create an instance of CustomAttributeTypedArgument
            //instance = new CustomAttributeTypedArgument();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomAttributeTypedArgument
        /// </summary>
        [Fact]
        public void CustomAttributeTypedArgumentInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomAttributeTypedArgument
            //Assert.IsType<CustomAttributeTypedArgument>(instance);
        }


        /// <summary>
        /// Test the property 'ArgumentType'
        /// </summary>
        [Fact]
        public void ArgumentTypeTest()
        {
            // TODO unit test for the property 'ArgumentType'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
