/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing EncoderLoadedMessageAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EncoderLoadedMessageAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EncoderLoadedMessageAllOf
        //private EncoderLoadedMessageAllOf instance;

        public EncoderLoadedMessageAllOfTests()
        {
            // TODO uncomment below to create an instance of EncoderLoadedMessageAllOf
            //instance = new EncoderLoadedMessageAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EncoderLoadedMessageAllOf
        /// </summary>
        [Fact]
        public void EncoderLoadedMessageAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" EncoderLoadedMessageAllOf
            //Assert.IsType<EncoderLoadedMessageAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'EncoderId'
        /// </summary>
        [Fact]
        public void EncoderIdTest()
        {
            // TODO unit test for the property 'EncoderId'
        }
        /// <summary>
        /// Test the property 'EncoderIndex'
        /// </summary>
        [Fact]
        public void EncoderIndexTest()
        {
            // TODO unit test for the property 'EncoderIndex'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Fact]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }

    }

}
