/*
 * aida-mini
 *
 * 1.0.522
 *
 * The version of the OpenAPI document: 1.0.522
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing EventInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventInfo
        //private EventInfo instance;

        public EventInfoTests()
        {
            // TODO uncomment below to create an instance of EventInfo
            //instance = new EventInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventInfo
        /// </summary>
        [Fact]
        public void EventInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventInfo
            //Assert.IsType<EventInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DeclaringType'
        /// </summary>
        [Fact]
        public void DeclaringTypeTest()
        {
            // TODO unit test for the property 'DeclaringType'
        }
        /// <summary>
        /// Test the property 'ReflectedType'
        /// </summary>
        [Fact]
        public void ReflectedTypeTest()
        {
            // TODO unit test for the property 'ReflectedType'
        }
        /// <summary>
        /// Test the property 'Module'
        /// </summary>
        [Fact]
        public void ModuleTest()
        {
            // TODO unit test for the property 'Module'
        }
        /// <summary>
        /// Test the property 'CustomAttributes'
        /// </summary>
        [Fact]
        public void CustomAttributesTest()
        {
            // TODO unit test for the property 'CustomAttributes'
        }
        /// <summary>
        /// Test the property 'IsCollectible'
        /// </summary>
        [Fact]
        public void IsCollectibleTest()
        {
            // TODO unit test for the property 'IsCollectible'
        }
        /// <summary>
        /// Test the property 'MetadataToken'
        /// </summary>
        [Fact]
        public void MetadataTokenTest()
        {
            // TODO unit test for the property 'MetadataToken'
        }
        /// <summary>
        /// Test the property 'MemberType'
        /// </summary>
        [Fact]
        public void MemberTypeTest()
        {
            // TODO unit test for the property 'MemberType'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'IsSpecialName'
        /// </summary>
        [Fact]
        public void IsSpecialNameTest()
        {
            // TODO unit test for the property 'IsSpecialName'
        }
        /// <summary>
        /// Test the property 'AddMethod'
        /// </summary>
        [Fact]
        public void AddMethodTest()
        {
            // TODO unit test for the property 'AddMethod'
        }
        /// <summary>
        /// Test the property 'RemoveMethod'
        /// </summary>
        [Fact]
        public void RemoveMethodTest()
        {
            // TODO unit test for the property 'RemoveMethod'
        }
        /// <summary>
        /// Test the property 'RaiseMethod'
        /// </summary>
        [Fact]
        public void RaiseMethodTest()
        {
            // TODO unit test for the property 'RaiseMethod'
        }
        /// <summary>
        /// Test the property 'IsMulticast'
        /// </summary>
        [Fact]
        public void IsMulticastTest()
        {
            // TODO unit test for the property 'IsMulticast'
        }
        /// <summary>
        /// Test the property 'EventHandlerType'
        /// </summary>
        [Fact]
        public void EventHandlerTypeTest()
        {
            // TODO unit test for the property 'EventHandlerType'
        }

    }

}
