/*
 * aida-mini
 *
 * 1.0.522
 *
 * The version of the OpenAPI document: 1.0.522
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing Module
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModuleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Module
        //private Module instance;

        public ModuleTests()
        {
            // TODO uncomment below to create an instance of Module
            //instance = new Module();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Module
        /// </summary>
        [Fact]
        public void ModuleInstanceTest()
        {
            // TODO uncomment below to test "IsType" Module
            //Assert.IsType<Module>(instance);
        }


        /// <summary>
        /// Test the property 'Assembly'
        /// </summary>
        [Fact]
        public void AssemblyTest()
        {
            // TODO unit test for the property 'Assembly'
        }
        /// <summary>
        /// Test the property 'FullyQualifiedName'
        /// </summary>
        [Fact]
        public void FullyQualifiedNameTest()
        {
            // TODO unit test for the property 'FullyQualifiedName'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'MdStreamVersion'
        /// </summary>
        [Fact]
        public void MdStreamVersionTest()
        {
            // TODO unit test for the property 'MdStreamVersion'
        }
        /// <summary>
        /// Test the property 'ModuleVersionId'
        /// </summary>
        [Fact]
        public void ModuleVersionIdTest()
        {
            // TODO unit test for the property 'ModuleVersionId'
        }
        /// <summary>
        /// Test the property 'ScopeName'
        /// </summary>
        [Fact]
        public void ScopeNameTest()
        {
            // TODO unit test for the property 'ScopeName'
        }
        /// <summary>
        /// Test the property 'ModuleHandle'
        /// </summary>
        [Fact]
        public void ModuleHandleTest()
        {
            // TODO unit test for the property 'ModuleHandle'
        }
        /// <summary>
        /// Test the property 'CustomAttributes'
        /// </summary>
        [Fact]
        public void CustomAttributesTest()
        {
            // TODO unit test for the property 'CustomAttributes'
        }
        /// <summary>
        /// Test the property 'MetadataToken'
        /// </summary>
        [Fact]
        public void MetadataTokenTest()
        {
            // TODO unit test for the property 'MetadataToken'
        }

    }

}
