/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing MySqlDataSourceConfigurationDtoAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MySqlDataSourceConfigurationDtoAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MySqlDataSourceConfigurationDtoAllOf
        //private MySqlDataSourceConfigurationDtoAllOf instance;

        public MySqlDataSourceConfigurationDtoAllOfTests()
        {
            // TODO uncomment below to create an instance of MySqlDataSourceConfigurationDtoAllOf
            //instance = new MySqlDataSourceConfigurationDtoAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MySqlDataSourceConfigurationDtoAllOf
        /// </summary>
        [Fact]
        public void MySqlDataSourceConfigurationDtoAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" MySqlDataSourceConfigurationDtoAllOf
            //Assert.IsType<MySqlDataSourceConfigurationDtoAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'TableName'
        /// </summary>
        [Fact]
        public void TableNameTest()
        {
            // TODO unit test for the property 'TableName'
        }
        /// <summary>
        /// Test the property 'QueryTemplate'
        /// </summary>
        [Fact]
        public void QueryTemplateTest()
        {
            // TODO unit test for the property 'QueryTemplate'
        }
        /// <summary>
        /// Test the property 'ConnectionString'
        /// </summary>
        [Fact]
        public void ConnectionStringTest()
        {
            // TODO unit test for the property 'ConnectionString'
        }
        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

    }

}
