/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing OcrReadBackMessageAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OcrReadBackMessageAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OcrReadBackMessageAllOf
        //private OcrReadBackMessageAllOf instance;

        public OcrReadBackMessageAllOfTests()
        {
            // TODO uncomment below to create an instance of OcrReadBackMessageAllOf
            //instance = new OcrReadBackMessageAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OcrReadBackMessageAllOf
        /// </summary>
        [Fact]
        public void OcrReadBackMessageAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" OcrReadBackMessageAllOf
            //Assert.IsType<OcrReadBackMessageAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'MeanConfidence'
        /// </summary>
        [Fact]
        public void MeanConfidenceTest()
        {
            // TODO unit test for the property 'MeanConfidence'
        }

    }

}
