/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing PersoProcessConfigurationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PersoProcessConfigurationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PersoProcessConfigurationDto
        //private PersoProcessConfigurationDto instance;

        public PersoProcessConfigurationDtoTests()
        {
            // TODO uncomment below to create an instance of PersoProcessConfigurationDto
            //instance = new PersoProcessConfigurationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PersoProcessConfigurationDto
        /// </summary>
        [Fact]
        public void PersoProcessConfigurationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PersoProcessConfigurationDto
            //Assert.IsType<PersoProcessConfigurationDto>(instance);
        }


        /// <summary>
        /// Test the property 'InputFeeder'
        /// </summary>
        [Fact]
        public void InputFeederTest()
        {
            // TODO unit test for the property 'InputFeeder'
        }
        /// <summary>
        /// Test the property 'FeedSide'
        /// </summary>
        [Fact]
        public void FeedSideTest()
        {
            // TODO unit test for the property 'FeedSide'
        }
        /// <summary>
        /// Test the property 'ReadBack'
        /// </summary>
        [Fact]
        public void ReadBackTest()
        {
            // TODO unit test for the property 'ReadBack'
        }

    }

}
