/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing RenameJobTemplateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RenameJobTemplateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RenameJobTemplateDto
        //private RenameJobTemplateDto instance;

        public RenameJobTemplateDtoTests()
        {
            // TODO uncomment below to create an instance of RenameJobTemplateDto
            //instance = new RenameJobTemplateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RenameJobTemplateDto
        /// </summary>
        [Fact]
        public void RenameJobTemplateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RenameJobTemplateDto
            //Assert.IsType<RenameJobTemplateDto>(instance);
        }


        /// <summary>
        /// Test the property 'NewName'
        /// </summary>
        [Fact]
        public void NewNameTest()
        {
            // TODO unit test for the property 'NewName'
        }
        /// <summary>
        /// Test the property 'OldName'
        /// </summary>
        [Fact]
        public void OldNameTest()
        {
            // TODO unit test for the property 'OldName'
        }

    }

}
