/*
 * aida-mini
 *
 * 1.3.5-dev.2+010ffe2cb3fa5597fddacb6f4c0bef4aefc1e852
 *
 * The version of the OpenAPI document: 1.3.5-dev.2+010ffe2cb3fa5597fddacb6f4c0bef4aefc1e852
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing SCardInitialization
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SCardInitializationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SCardInitialization
        //private SCardInitialization instance;

        public SCardInitializationTests()
        {
            // TODO uncomment below to create an instance of SCardInitialization
            //instance = new SCardInitialization();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SCardInitialization
        /// </summary>
        [Fact]
        public void SCardInitializationInstanceTest()
        {
            // TODO uncomment below to test "IsType" SCardInitialization
            //Assert.IsType<SCardInitialization>(instance);
        }



    }

}
