/*
 * aida-mini
 *
 * 1.0.522
 *
 * The version of the OpenAPI document: 1.0.522
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing TypeInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TypeInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TypeInfo
        //private TypeInfo instance;

        public TypeInfoTests()
        {
            // TODO uncomment below to create an instance of TypeInfo
            //instance = new TypeInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TypeInfo
        /// </summary>
        [Fact]
        public void TypeInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TypeInfo
            //Assert.IsType<TypeInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CustomAttributes'
        /// </summary>
        [Fact]
        public void CustomAttributesTest()
        {
            // TODO unit test for the property 'CustomAttributes'
        }
        /// <summary>
        /// Test the property 'IsCollectible'
        /// </summary>
        [Fact]
        public void IsCollectibleTest()
        {
            // TODO unit test for the property 'IsCollectible'
        }
        /// <summary>
        /// Test the property 'MetadataToken'
        /// </summary>
        [Fact]
        public void MetadataTokenTest()
        {
            // TODO unit test for the property 'MetadataToken'
        }
        /// <summary>
        /// Test the property 'IsInterface'
        /// </summary>
        [Fact]
        public void IsInterfaceTest()
        {
            // TODO unit test for the property 'IsInterface'
        }
        /// <summary>
        /// Test the property 'MemberType'
        /// </summary>
        [Fact]
        public void MemberTypeTest()
        {
            // TODO unit test for the property 'MemberType'
        }
        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
        /// <summary>
        /// Test the property 'AssemblyQualifiedName'
        /// </summary>
        [Fact]
        public void AssemblyQualifiedNameTest()
        {
            // TODO unit test for the property 'AssemblyQualifiedName'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'Assembly'
        /// </summary>
        [Fact]
        public void AssemblyTest()
        {
            // TODO unit test for the property 'Assembly'
        }
        /// <summary>
        /// Test the property 'Module'
        /// </summary>
        [Fact]
        public void ModuleTest()
        {
            // TODO unit test for the property 'Module'
        }
        /// <summary>
        /// Test the property 'IsNested'
        /// </summary>
        [Fact]
        public void IsNestedTest()
        {
            // TODO unit test for the property 'IsNested'
        }
        /// <summary>
        /// Test the property 'DeclaringType'
        /// </summary>
        [Fact]
        public void DeclaringTypeTest()
        {
            // TODO unit test for the property 'DeclaringType'
        }
        /// <summary>
        /// Test the property 'DeclaringMethod'
        /// </summary>
        [Fact]
        public void DeclaringMethodTest()
        {
            // TODO unit test for the property 'DeclaringMethod'
        }
        /// <summary>
        /// Test the property 'ReflectedType'
        /// </summary>
        [Fact]
        public void ReflectedTypeTest()
        {
            // TODO unit test for the property 'ReflectedType'
        }
        /// <summary>
        /// Test the property 'UnderlyingSystemType'
        /// </summary>
        [Fact]
        public void UnderlyingSystemTypeTest()
        {
            // TODO unit test for the property 'UnderlyingSystemType'
        }
        /// <summary>
        /// Test the property 'IsTypeDefinition'
        /// </summary>
        [Fact]
        public void IsTypeDefinitionTest()
        {
            // TODO unit test for the property 'IsTypeDefinition'
        }
        /// <summary>
        /// Test the property 'IsArray'
        /// </summary>
        [Fact]
        public void IsArrayTest()
        {
            // TODO unit test for the property 'IsArray'
        }
        /// <summary>
        /// Test the property 'IsByRef'
        /// </summary>
        [Fact]
        public void IsByRefTest()
        {
            // TODO unit test for the property 'IsByRef'
        }
        /// <summary>
        /// Test the property 'IsPointer'
        /// </summary>
        [Fact]
        public void IsPointerTest()
        {
            // TODO unit test for the property 'IsPointer'
        }
        /// <summary>
        /// Test the property 'IsConstructedGenericType'
        /// </summary>
        [Fact]
        public void IsConstructedGenericTypeTest()
        {
            // TODO unit test for the property 'IsConstructedGenericType'
        }
        /// <summary>
        /// Test the property 'IsGenericParameter'
        /// </summary>
        [Fact]
        public void IsGenericParameterTest()
        {
            // TODO unit test for the property 'IsGenericParameter'
        }
        /// <summary>
        /// Test the property 'IsGenericTypeParameter'
        /// </summary>
        [Fact]
        public void IsGenericTypeParameterTest()
        {
            // TODO unit test for the property 'IsGenericTypeParameter'
        }
        /// <summary>
        /// Test the property 'IsGenericMethodParameter'
        /// </summary>
        [Fact]
        public void IsGenericMethodParameterTest()
        {
            // TODO unit test for the property 'IsGenericMethodParameter'
        }
        /// <summary>
        /// Test the property 'IsGenericType'
        /// </summary>
        [Fact]
        public void IsGenericTypeTest()
        {
            // TODO unit test for the property 'IsGenericType'
        }
        /// <summary>
        /// Test the property 'IsGenericTypeDefinition'
        /// </summary>
        [Fact]
        public void IsGenericTypeDefinitionTest()
        {
            // TODO unit test for the property 'IsGenericTypeDefinition'
        }
        /// <summary>
        /// Test the property 'IsSZArray'
        /// </summary>
        [Fact]
        public void IsSZArrayTest()
        {
            // TODO unit test for the property 'IsSZArray'
        }
        /// <summary>
        /// Test the property 'IsVariableBoundArray'
        /// </summary>
        [Fact]
        public void IsVariableBoundArrayTest()
        {
            // TODO unit test for the property 'IsVariableBoundArray'
        }
        /// <summary>
        /// Test the property 'IsByRefLike'
        /// </summary>
        [Fact]
        public void IsByRefLikeTest()
        {
            // TODO unit test for the property 'IsByRefLike'
        }
        /// <summary>
        /// Test the property 'HasElementType'
        /// </summary>
        [Fact]
        public void HasElementTypeTest()
        {
            // TODO unit test for the property 'HasElementType'
        }
        /// <summary>
        /// Test the property 'GenericTypeArguments'
        /// </summary>
        [Fact]
        public void GenericTypeArgumentsTest()
        {
            // TODO unit test for the property 'GenericTypeArguments'
        }
        /// <summary>
        /// Test the property 'GenericParameterPosition'
        /// </summary>
        [Fact]
        public void GenericParameterPositionTest()
        {
            // TODO unit test for the property 'GenericParameterPosition'
        }
        /// <summary>
        /// Test the property 'GenericParameterAttributes'
        /// </summary>
        [Fact]
        public void GenericParameterAttributesTest()
        {
            // TODO unit test for the property 'GenericParameterAttributes'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'IsAbstract'
        /// </summary>
        [Fact]
        public void IsAbstractTest()
        {
            // TODO unit test for the property 'IsAbstract'
        }
        /// <summary>
        /// Test the property 'IsImport'
        /// </summary>
        [Fact]
        public void IsImportTest()
        {
            // TODO unit test for the property 'IsImport'
        }
        /// <summary>
        /// Test the property 'IsSealed'
        /// </summary>
        [Fact]
        public void IsSealedTest()
        {
            // TODO unit test for the property 'IsSealed'
        }
        /// <summary>
        /// Test the property 'IsSpecialName'
        /// </summary>
        [Fact]
        public void IsSpecialNameTest()
        {
            // TODO unit test for the property 'IsSpecialName'
        }
        /// <summary>
        /// Test the property 'IsClass'
        /// </summary>
        [Fact]
        public void IsClassTest()
        {
            // TODO unit test for the property 'IsClass'
        }
        /// <summary>
        /// Test the property 'IsNestedAssembly'
        /// </summary>
        [Fact]
        public void IsNestedAssemblyTest()
        {
            // TODO unit test for the property 'IsNestedAssembly'
        }
        /// <summary>
        /// Test the property 'IsNestedFamANDAssem'
        /// </summary>
        [Fact]
        public void IsNestedFamANDAssemTest()
        {
            // TODO unit test for the property 'IsNestedFamANDAssem'
        }
        /// <summary>
        /// Test the property 'IsNestedFamily'
        /// </summary>
        [Fact]
        public void IsNestedFamilyTest()
        {
            // TODO unit test for the property 'IsNestedFamily'
        }
        /// <summary>
        /// Test the property 'IsNestedFamORAssem'
        /// </summary>
        [Fact]
        public void IsNestedFamORAssemTest()
        {
            // TODO unit test for the property 'IsNestedFamORAssem'
        }
        /// <summary>
        /// Test the property 'IsNestedPrivate'
        /// </summary>
        [Fact]
        public void IsNestedPrivateTest()
        {
            // TODO unit test for the property 'IsNestedPrivate'
        }
        /// <summary>
        /// Test the property 'IsNestedPublic'
        /// </summary>
        [Fact]
        public void IsNestedPublicTest()
        {
            // TODO unit test for the property 'IsNestedPublic'
        }
        /// <summary>
        /// Test the property 'IsNotPublic'
        /// </summary>
        [Fact]
        public void IsNotPublicTest()
        {
            // TODO unit test for the property 'IsNotPublic'
        }
        /// <summary>
        /// Test the property 'IsPublic'
        /// </summary>
        [Fact]
        public void IsPublicTest()
        {
            // TODO unit test for the property 'IsPublic'
        }
        /// <summary>
        /// Test the property 'IsAutoLayout'
        /// </summary>
        [Fact]
        public void IsAutoLayoutTest()
        {
            // TODO unit test for the property 'IsAutoLayout'
        }
        /// <summary>
        /// Test the property 'IsExplicitLayout'
        /// </summary>
        [Fact]
        public void IsExplicitLayoutTest()
        {
            // TODO unit test for the property 'IsExplicitLayout'
        }
        /// <summary>
        /// Test the property 'IsLayoutSequential'
        /// </summary>
        [Fact]
        public void IsLayoutSequentialTest()
        {
            // TODO unit test for the property 'IsLayoutSequential'
        }
        /// <summary>
        /// Test the property 'IsAnsiClass'
        /// </summary>
        [Fact]
        public void IsAnsiClassTest()
        {
            // TODO unit test for the property 'IsAnsiClass'
        }
        /// <summary>
        /// Test the property 'IsAutoClass'
        /// </summary>
        [Fact]
        public void IsAutoClassTest()
        {
            // TODO unit test for the property 'IsAutoClass'
        }
        /// <summary>
        /// Test the property 'IsUnicodeClass'
        /// </summary>
        [Fact]
        public void IsUnicodeClassTest()
        {
            // TODO unit test for the property 'IsUnicodeClass'
        }
        /// <summary>
        /// Test the property 'IsCOMObject'
        /// </summary>
        [Fact]
        public void IsCOMObjectTest()
        {
            // TODO unit test for the property 'IsCOMObject'
        }
        /// <summary>
        /// Test the property 'IsContextful'
        /// </summary>
        [Fact]
        public void IsContextfulTest()
        {
            // TODO unit test for the property 'IsContextful'
        }
        /// <summary>
        /// Test the property 'IsEnum'
        /// </summary>
        [Fact]
        public void IsEnumTest()
        {
            // TODO unit test for the property 'IsEnum'
        }
        /// <summary>
        /// Test the property 'IsMarshalByRef'
        /// </summary>
        [Fact]
        public void IsMarshalByRefTest()
        {
            // TODO unit test for the property 'IsMarshalByRef'
        }
        /// <summary>
        /// Test the property 'IsPrimitive'
        /// </summary>
        [Fact]
        public void IsPrimitiveTest()
        {
            // TODO unit test for the property 'IsPrimitive'
        }
        /// <summary>
        /// Test the property 'IsValueType'
        /// </summary>
        [Fact]
        public void IsValueTypeTest()
        {
            // TODO unit test for the property 'IsValueType'
        }
        /// <summary>
        /// Test the property 'IsSignatureType'
        /// </summary>
        [Fact]
        public void IsSignatureTypeTest()
        {
            // TODO unit test for the property 'IsSignatureType'
        }
        /// <summary>
        /// Test the property 'IsSecurityCritical'
        /// </summary>
        [Fact]
        public void IsSecurityCriticalTest()
        {
            // TODO unit test for the property 'IsSecurityCritical'
        }
        /// <summary>
        /// Test the property 'IsSecuritySafeCritical'
        /// </summary>
        [Fact]
        public void IsSecuritySafeCriticalTest()
        {
            // TODO unit test for the property 'IsSecuritySafeCritical'
        }
        /// <summary>
        /// Test the property 'IsSecurityTransparent'
        /// </summary>
        [Fact]
        public void IsSecurityTransparentTest()
        {
            // TODO unit test for the property 'IsSecurityTransparent'
        }
        /// <summary>
        /// Test the property 'StructLayoutAttribute'
        /// </summary>
        [Fact]
        public void StructLayoutAttributeTest()
        {
            // TODO unit test for the property 'StructLayoutAttribute'
        }
        /// <summary>
        /// Test the property 'TypeInitializer'
        /// </summary>
        [Fact]
        public void TypeInitializerTest()
        {
            // TODO unit test for the property 'TypeInitializer'
        }
        /// <summary>
        /// Test the property 'TypeHandle'
        /// </summary>
        [Fact]
        public void TypeHandleTest()
        {
            // TODO unit test for the property 'TypeHandle'
        }
        /// <summary>
        /// Test the property 'Guid'
        /// </summary>
        [Fact]
        public void GuidTest()
        {
            // TODO unit test for the property 'Guid'
        }
        /// <summary>
        /// Test the property 'BaseType'
        /// </summary>
        [Fact]
        public void BaseTypeTest()
        {
            // TODO unit test for the property 'BaseType'
        }
        /// <summary>
        /// Test the property 'IsSerializable'
        /// </summary>
        [Fact]
        public void IsSerializableTest()
        {
            // TODO unit test for the property 'IsSerializable'
        }
        /// <summary>
        /// Test the property 'ContainsGenericParameters'
        /// </summary>
        [Fact]
        public void ContainsGenericParametersTest()
        {
            // TODO unit test for the property 'ContainsGenericParameters'
        }
        /// <summary>
        /// Test the property 'IsVisible'
        /// </summary>
        [Fact]
        public void IsVisibleTest()
        {
            // TODO unit test for the property 'IsVisible'
        }
        /// <summary>
        /// Test the property 'GenericTypeParameters'
        /// </summary>
        [Fact]
        public void GenericTypeParametersTest()
        {
            // TODO unit test for the property 'GenericTypeParameters'
        }
        /// <summary>
        /// Test the property 'DeclaredConstructors'
        /// </summary>
        [Fact]
        public void DeclaredConstructorsTest()
        {
            // TODO unit test for the property 'DeclaredConstructors'
        }
        /// <summary>
        /// Test the property 'DeclaredEvents'
        /// </summary>
        [Fact]
        public void DeclaredEventsTest()
        {
            // TODO unit test for the property 'DeclaredEvents'
        }
        /// <summary>
        /// Test the property 'DeclaredFields'
        /// </summary>
        [Fact]
        public void DeclaredFieldsTest()
        {
            // TODO unit test for the property 'DeclaredFields'
        }
        /// <summary>
        /// Test the property 'DeclaredMembers'
        /// </summary>
        [Fact]
        public void DeclaredMembersTest()
        {
            // TODO unit test for the property 'DeclaredMembers'
        }
        /// <summary>
        /// Test the property 'DeclaredMethods'
        /// </summary>
        [Fact]
        public void DeclaredMethodsTest()
        {
            // TODO unit test for the property 'DeclaredMethods'
        }
        /// <summary>
        /// Test the property 'DeclaredNestedTypes'
        /// </summary>
        [Fact]
        public void DeclaredNestedTypesTest()
        {
            // TODO unit test for the property 'DeclaredNestedTypes'
        }
        /// <summary>
        /// Test the property 'DeclaredProperties'
        /// </summary>
        [Fact]
        public void DeclaredPropertiesTest()
        {
            // TODO unit test for the property 'DeclaredProperties'
        }
        /// <summary>
        /// Test the property 'ImplementedInterfaces'
        /// </summary>
        [Fact]
        public void ImplementedInterfacesTest()
        {
            // TODO unit test for the property 'ImplementedInterfaces'
        }

    }

}
