/*
 * aida-mini
 *
 * 1.0.522
 *
 * The version of the OpenAPI document: 1.0.522
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing TypeAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TypeAttributesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TypeAttributes
        //private TypeAttributes instance;

        public TypeAttributesTests()
        {
            // TODO uncomment below to create an instance of TypeAttributes
            //instance = new TypeAttributes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TypeAttributes
        /// </summary>
        [Fact]
        public void TypeAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsType" TypeAttributes
            //Assert.IsType<TypeAttributes>(instance);
        }



    }

}
