/*
 * aida-mini
 *
 * 1.0.522
 *
 * The version of the OpenAPI document: 1.0.522
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing WorkflowOutputReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkflowOutputReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkflowOutputReference
        //private WorkflowOutputReference instance;

        public WorkflowOutputReferenceTests()
        {
            // TODO uncomment below to create an instance of WorkflowOutputReference
            //instance = new WorkflowOutputReference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkflowOutputReference
        /// </summary>
        [Fact]
        public void WorkflowOutputReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkflowOutputReference
            //Assert.IsType<WorkflowOutputReference>(instance);
        }


        /// <summary>
        /// Test the property 'ProviderName'
        /// </summary>
        [Fact]
        public void ProviderNameTest()
        {
            // TODO unit test for the property 'ProviderName'
        }
        /// <summary>
        /// Test the property 'ActivityId'
        /// </summary>
        [Fact]
        public void ActivityIdTest()
        {
            // TODO unit test for the property 'ActivityId'
        }

    }

}
