/*
 * aida-mini
 *
 * 1.3.5+5a9fb622482f18d24fc4f1b5ae8fe290f7c62728
 *
 * The version of the OpenAPI document: 1.3.5+5a9fb622482f18d24fc4f1b5ae8fe290f7c62728
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing WorkflowSchedulerStoppedMessageAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkflowSchedulerStoppedMessageAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkflowSchedulerStoppedMessageAllOf
        //private WorkflowSchedulerStoppedMessageAllOf instance;

        public WorkflowSchedulerStoppedMessageAllOfTests()
        {
            // TODO uncomment below to create an instance of WorkflowSchedulerStoppedMessageAllOf
            //instance = new WorkflowSchedulerStoppedMessageAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkflowSchedulerStoppedMessageAllOf
        /// </summary>
        [Fact]
        public void WorkflowSchedulerStoppedMessageAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkflowSchedulerStoppedMessageAllOf
            //Assert.IsType<WorkflowSchedulerStoppedMessageAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'StopReason'
        /// </summary>
        [Fact]
        public void StopReasonTest()
        {
            // TODO unit test for the property 'StopReason'
        }

    }

}
