/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Mini.Api;
using Aida.Sdk.Mini.Model;
using Aida.Sdk.Mini.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Mini.Test.Model
{
    /// <summary>
    ///  Class for testing XPrintCartridgeSlotStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XPrintCartridgeSlotStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XPrintCartridgeSlotStatus
        //private XPrintCartridgeSlotStatus instance;

        public XPrintCartridgeSlotStatusTests()
        {
            // TODO uncomment below to create an instance of XPrintCartridgeSlotStatus
            //instance = new XPrintCartridgeSlotStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XPrintCartridgeSlotStatus
        /// </summary>
        [Fact]
        public void XPrintCartridgeSlotStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" XPrintCartridgeSlotStatus
            //Assert.IsType<XPrintCartridgeSlotStatus>(instance);
        }



    }

}
