/*
 * aida-mini
 *
 * 1.3.5-dev.2+010ffe2cb3fa5597fddacb6f4c0bef4aefc1e852
 *
 * The version of the OpenAPI document: 1.3.5-dev.2+010ffe2cb3fa5597fddacb6f4c0bef4aefc1e852
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Polly;
using System.Net.Http;

namespace Aida.Sdk.Mini.Client
{
    /// <summary>
    /// Configuration class to set the polly retry policies to be applied to the requests.
    /// </summary>
    public static class RetryConfiguration
    {
        /// <summary>
        /// Retry policy
        /// </summary>
        public static Policy<HttpResponseMessage> RetryPolicy { get; set; }

        /// <summary>
        /// Async retry policy
        /// </summary>
        public static AsyncPolicy<HttpResponseMessage> AsyncRetryPolicy { get; set; }
    }
}
