/*
 * aida
 *
 * 1.0.722-rc.3+496a5e11f6297a76e2b83a2b26e743e21a1c18c1
 *
 * The version of the OpenAPI document: 1.0.722-rc.3+496a5e11f6297a76e2b83a2b26e743e21a1c18c1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// Defines PrinterActionErrorCodes
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PrinterActionErrorCodes
    {
        /// <summary>
        /// Enum NoErrors for value: NoErrors
        /// </summary>
        [EnumMember(Value = "NoErrors")]
        NoErrors = 1,

        /// <summary>
        /// Enum FeederEmpty for value: FeederEmpty
        /// </summary>
        [EnumMember(Value = "FeederEmpty")]
        FeederEmpty = 2,

        /// <summary>
        /// Enum NoPassportLoaded for value: NoPassportLoaded
        /// </summary>
        [EnumMember(Value = "NoPassportLoaded")]
        NoPassportLoaded = 3,

        /// <summary>
        /// Enum PrinterBusy for value: PrinterBusy
        /// </summary>
        [EnumMember(Value = "PrinterBusy")]
        PrinterBusy = 4,

        /// <summary>
        /// Enum PrinterError for value: PrinterError
        /// </summary>
        [EnumMember(Value = "PrinterError")]
        PrinterError = 5,

        /// <summary>
        /// Enum PrinterBoardCommunicationError for value: PrinterBoardCommunicationError
        /// </summary>
        [EnumMember(Value = "PrinterBoardCommunicationError")]
        PrinterBoardCommunicationError = 6,

        /// <summary>
        /// Enum PrintJobEmpty for value: PrintJobEmpty
        /// </summary>
        [EnumMember(Value = "PrintJobEmpty")]
        PrintJobEmpty = 7,

        /// <summary>
        /// Enum PrintJobOutOfBounds for value: PrintJobOutOfBounds
        /// </summary>
        [EnumMember(Value = "PrintJobOutOfBounds")]
        PrintJobOutOfBounds = 8,

        /// <summary>
        /// Enum PrintJobCancelled for value: PrintJobCancelled
        /// </summary>
        [EnumMember(Value = "PrintJobCancelled")]
        PrintJobCancelled = 9,

        /// <summary>
        /// Enum AutoCleanFailed for value: AutoCleanFailed
        /// </summary>
        [EnumMember(Value = "AutoCleanFailed")]
        AutoCleanFailed = 10,

        /// <summary>
        /// Enum PrintProcessFailed for value: PrintProcessFailed
        /// </summary>
        [EnumMember(Value = "PrintProcessFailed")]
        PrintProcessFailed = 11,

        /// <summary>
        /// Enum PrintheadBoardError for value: PrintheadBoardError
        /// </summary>
        [EnumMember(Value = "PrintheadBoardError")]
        PrintheadBoardError = 12,

        /// <summary>
        /// Enum PrintApplicationError for value: PrintApplicationError
        /// </summary>
        [EnumMember(Value = "PrintApplicationError")]
        PrintApplicationError = 13,

        /// <summary>
        /// Enum InvalidDataPageId for value: InvalidDataPageId
        /// </summary>
        [EnumMember(Value = "InvalidDataPageId")]
        InvalidDataPageId = 14

    }

}
