/*
 * aida
 *
 * 1.0.722-rc.3+496a5e11f6297a76e2b83a2b26e743e21a1c18c1
 *
 * The version of the OpenAPI document: 1.0.722-rc.3+496a5e11f6297a76e2b83a2b26e743e21a1c18c1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// ReadHoldingRegistersRequest
    /// </summary>
    [DataContract(Name = "ReadHoldingRegistersRequest")]
    public partial class ReadHoldingRegistersRequest : IEquatable<ReadHoldingRegistersRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReadHoldingRegistersRequest" /> class.
        /// </summary>
        /// <param name="slaveId">slaveId.</param>
        /// <param name="address">address.</param>
        /// <param name="length">length.</param>
        public ReadHoldingRegistersRequest(int slaveId = default(int), int address = default(int), int length = default(int))
        {
            this.SlaveId = slaveId;
            this.Address = address;
            this.Length = length;
        }

        /// <summary>
        /// Gets or Sets SlaveId
        /// </summary>
        [DataMember(Name = "slaveId", EmitDefaultValue = false)]
        public int SlaveId { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name = "address", EmitDefaultValue = false)]
        public int Address { get; set; }

        /// <summary>
        /// Gets or Sets Length
        /// </summary>
        [DataMember(Name = "length", EmitDefaultValue = false)]
        public int Length { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReadHoldingRegistersRequest {\n");
            sb.Append("  SlaveId: ").Append(SlaveId).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReadHoldingRegistersRequest);
        }

        /// <summary>
        /// Returns true if ReadHoldingRegistersRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ReadHoldingRegistersRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReadHoldingRegistersRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SlaveId == input.SlaveId ||
                    this.SlaveId.Equals(input.SlaveId)
                ) && 
                (
                    this.Address == input.Address ||
                    this.Address.Equals(input.Address)
                ) && 
                (
                    this.Length == input.Length ||
                    this.Length.Equals(input.Length)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.SlaveId.GetHashCode();
                hashCode = (hashCode * 59) + this.Address.GetHashCode();
                hashCode = (hashCode * 59) + this.Length.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
