/*
 * aida
 *
 * 1.0.385
 *
 * The version of the OpenAPI document: 1.0.385
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// Defines WorkflowSchedulerStopReason
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WorkflowSchedulerStopReason
    {
        /// <summary>
        /// Enum BatchCompleted for value: BatchCompleted
        /// </summary>
        [EnumMember(Value = "BatchCompleted")]
        BatchCompleted = 1,

        /// <summary>
        /// Enum FeederEmpty for value: FeederEmpty
        /// </summary>
        [EnumMember(Value = "FeederEmpty")]
        FeederEmpty = 2,

        /// <summary>
        /// Enum ManualStop for value: ManualStop
        /// </summary>
        [EnumMember(Value = "ManualStop")]
        ManualStop = 3,

        /// <summary>
        /// Enum CardJam for value: CardJam
        /// </summary>
        [EnumMember(Value = "CardJam")]
        CardJam = 4,

        /// <summary>
        /// Enum UnhandledException for value: UnhandledException
        /// </summary>
        [EnumMember(Value = "UnhandledException")]
        UnhandledException = 5,

        /// <summary>
        /// Enum WebhooksServerUnreachable for value: WebhooksServerUnreachable
        /// </summary>
        [EnumMember(Value = "WebhooksServerUnreachable")]
        WebhooksServerUnreachable = 6

    }

}
