/*
 * aida
 *
 * 1.0.722-rc.3+496a5e11f6297a76e2b83a2b26e743e21a1c18c1
 *
 * The version of the OpenAPI document: 1.0.722-rc.3+496a5e11f6297a76e2b83a2b26e743e21a1c18c1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// Defines XPrintCappingInfo
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum XPrintCappingInfo
    {
        /// <summary>
        /// Enum WiperUp for value: WiperUp
        /// </summary>
        [EnumMember(Value = "WiperUp")]
        WiperUp = 1,

        /// <summary>
        /// Enum CappingUp for value: CappingUp
        /// </summary>
        [EnumMember(Value = "CappingUp")]
        CappingUp = 2,

        /// <summary>
        /// Enum CappingPumpOn for value: CappingPumpOn
        /// </summary>
        [EnumMember(Value = "CappingPumpOn")]
        CappingPumpOn = 3,

        /// <summary>
        /// Enum CappingShieldUp for value: CappingShieldUp
        /// </summary>
        [EnumMember(Value = "CappingShieldUp")]
        CappingShieldUp = 4

    }

}
