/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Mini.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Mini.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Mini.Model
{
    /// <summary>
    /// CartridgeHolderSlotDto
    /// </summary>
    [DataContract(Name = "CartridgeHolderSlotDto")]
    public partial class CartridgeHolderSlotDto : IEquatable<CartridgeHolderSlotDto>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets SlotStatus
        /// </summary>
        [DataMember(Name = "slotStatus", EmitDefaultValue = false)]
        public XPrintCartridgeSlotStatus? SlotStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CartridgeHolderSlotDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CartridgeHolderSlotDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CartridgeHolderSlotDto" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="cartridge">cartridge.</param>
        /// <param name="slotStatus">slotStatus.</param>
        /// <param name="fluidExpected">fluidExpected.</param>
        public CartridgeHolderSlotDto(int id = default(int), CartridgeDto cartridge = default(CartridgeDto), XPrintCartridgeSlotStatus? slotStatus = default(XPrintCartridgeSlotStatus?), FluidDto fluidExpected = default(FluidDto))
        {
            this.Id = id;
            this.Cartridge = cartridge;
            this.SlotStatus = slotStatus;
            this.FluidExpected = fluidExpected;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Cartridge
        /// </summary>
        [DataMember(Name = "cartridge", EmitDefaultValue = false)]
        public CartridgeDto Cartridge { get; set; }

        /// <summary>
        /// Gets or Sets FluidExpected
        /// </summary>
        [DataMember(Name = "fluidExpected", EmitDefaultValue = false)]
        public FluidDto FluidExpected { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CartridgeHolderSlotDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Cartridge: ").Append(Cartridge).Append("\n");
            sb.Append("  SlotStatus: ").Append(SlotStatus).Append("\n");
            sb.Append("  FluidExpected: ").Append(FluidExpected).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CartridgeHolderSlotDto);
        }

        /// <summary>
        /// Returns true if CartridgeHolderSlotDto instances are equal
        /// </summary>
        /// <param name="input">Instance of CartridgeHolderSlotDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CartridgeHolderSlotDto input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.Cartridge == input.Cartridge ||
                    (this.Cartridge != null &&
                    this.Cartridge.Equals(input.Cartridge))
                ) && 
                (
                    this.SlotStatus == input.SlotStatus ||
                    this.SlotStatus.Equals(input.SlotStatus)
                ) && 
                (
                    this.FluidExpected == input.FluidExpected ||
                    (this.FluidExpected != null &&
                    this.FluidExpected.Equals(input.FluidExpected))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.Cartridge != null)
                {
                    hashCode = (hashCode * 59) + this.Cartridge.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.SlotStatus.GetHashCode();
                if (this.FluidExpected != null)
                {
                    hashCode = (hashCode * 59) + this.FluidExpected.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
