/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Mini.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Mini.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Mini.Model
{
    /// <summary>
    /// CartridgeDto
    /// </summary>
    [DataContract(Name = "CartridgeDto")]
    public partial class CartridgeDto : IEquatable<CartridgeDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartridgeDto" /> class.
        /// </summary>
        /// <param name="serialNumber">serialNumber.</param>
        /// <param name="fluid">fluid.</param>
        /// <param name="inkExpireDate">inkExpireDate.</param>
        /// <param name="inkLevel">inkLevel.</param>
        public CartridgeDto(int serialNumber = default(int), FluidDto fluid = default(FluidDto), DateTime? inkExpireDate = default(DateTime?), int inkLevel = default(int))
        {
            this.SerialNumber = serialNumber;
            this.Fluid = fluid;
            this.InkExpireDate = inkExpireDate;
            this.InkLevel = inkLevel;
        }

        /// <summary>
        /// Gets or Sets SerialNumber
        /// </summary>
        [DataMember(Name = "serialNumber", EmitDefaultValue = false)]
        public int SerialNumber { get; set; }

        /// <summary>
        /// Gets or Sets Fluid
        /// </summary>
        [DataMember(Name = "fluid", EmitDefaultValue = false)]
        public FluidDto Fluid { get; set; }

        /// <summary>
        /// Gets or Sets InkExpireDate
        /// </summary>
        [DataMember(Name = "inkExpireDate", EmitDefaultValue = true)]
        public DateTime? InkExpireDate { get; set; }

        /// <summary>
        /// Gets or Sets InkLevel
        /// </summary>
        [DataMember(Name = "inkLevel", EmitDefaultValue = false)]
        public int InkLevel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CartridgeDto {\n");
            sb.Append("  SerialNumber: ").Append(SerialNumber).Append("\n");
            sb.Append("  Fluid: ").Append(Fluid).Append("\n");
            sb.Append("  InkExpireDate: ").Append(InkExpireDate).Append("\n");
            sb.Append("  InkLevel: ").Append(InkLevel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CartridgeDto);
        }

        /// <summary>
        /// Returns true if CartridgeDto instances are equal
        /// </summary>
        /// <param name="input">Instance of CartridgeDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CartridgeDto input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SerialNumber == input.SerialNumber ||
                    this.SerialNumber.Equals(input.SerialNumber)
                ) && 
                (
                    this.Fluid == input.Fluid ||
                    (this.Fluid != null &&
                    this.Fluid.Equals(input.Fluid))
                ) && 
                (
                    this.InkExpireDate == input.InkExpireDate ||
                    (this.InkExpireDate != null &&
                    this.InkExpireDate.Equals(input.InkExpireDate))
                ) && 
                (
                    this.InkLevel == input.InkLevel ||
                    this.InkLevel.Equals(input.InkLevel)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.SerialNumber.GetHashCode();
                if (this.Fluid != null)
                {
                    hashCode = (hashCode * 59) + this.Fluid.GetHashCode();
                }
                if (this.InkExpireDate != null)
                {
                    hashCode = (hashCode * 59) + this.InkExpireDate.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.InkLevel.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
