/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Mini.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Mini.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Mini.Model
{
    /// <summary>
    /// ChipReadBackConfigurationDtoAllOf
    /// </summary>
    [DataContract(Name = "ChipReadBackConfigurationDto_allOf")]
    public partial class ChipReadBackConfigurationDtoAllOf : IEquatable<ChipReadBackConfigurationDtoAllOf>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets ReaderAccessType
        /// </summary>
        [DataMember(Name = "readerAccessType", EmitDefaultValue = false)]
        public ReaderAccessType? ReaderAccessType { get; set; }

        /// <summary>
        /// Gets or Sets ReaderInterfaceType
        /// </summary>
        [DataMember(Name = "readerInterfaceType", EmitDefaultValue = false)]
        public ReaderInterfaceType? ReaderInterfaceType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChipReadBackConfigurationDtoAllOf" /> class.
        /// </summary>
        /// <param name="readerAccessType">readerAccessType.</param>
        /// <param name="readerInterfaceType">readerInterfaceType.</param>
        public ChipReadBackConfigurationDtoAllOf(ReaderAccessType? readerAccessType = default(ReaderAccessType?), ReaderInterfaceType? readerInterfaceType = default(ReaderInterfaceType?))
        {
            this.ReaderAccessType = readerAccessType;
            this.ReaderInterfaceType = readerInterfaceType;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChipReadBackConfigurationDtoAllOf {\n");
            sb.Append("  ReaderAccessType: ").Append(ReaderAccessType).Append("\n");
            sb.Append("  ReaderInterfaceType: ").Append(ReaderInterfaceType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ChipReadBackConfigurationDtoAllOf);
        }

        /// <summary>
        /// Returns true if ChipReadBackConfigurationDtoAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of ChipReadBackConfigurationDtoAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChipReadBackConfigurationDtoAllOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ReaderAccessType == input.ReaderAccessType ||
                    this.ReaderAccessType.Equals(input.ReaderAccessType)
                ) && 
                (
                    this.ReaderInterfaceType == input.ReaderInterfaceType ||
                    this.ReaderInterfaceType.Equals(input.ReaderInterfaceType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ReaderAccessType.GetHashCode();
                hashCode = (hashCode * 59) + this.ReaderInterfaceType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
