/*
 * aida-mini
 *
 * 1.3.5+5a9fb622482f18d24fc4f1b5ae8fe290f7c62728
 *
 * The version of the OpenAPI document: 1.3.5+5a9fb622482f18d24fc4f1b5ae8fe290f7c62728
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Mini.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Mini.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Mini.Model
{
    /// <summary>
    /// Defines ReaderInterfaceType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ReaderInterfaceType
    {
        /// <summary>
        /// Enum Contact for value: Contact
        /// </summary>
        [EnumMember(Value = "Contact")]
        Contact = 1,

        /// <summary>
        /// Enum Contactless for value: Contactless
        /// </summary>
        [EnumMember(Value = "Contactless")]
        Contactless = 2

    }

}
