/*
 * aida-mini
 *
 * 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 *
 * The version of the OpenAPI document: 1.6.2+41397a726a6023bf59f48e050c6a3985450c62e2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Mini.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Mini.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Mini.Model
{
    /// <summary>
    /// RenameJobTemplateDto
    /// </summary>
    [DataContract(Name = "RenameJobTemplateDto")]
    public partial class RenameJobTemplateDto : IEquatable<RenameJobTemplateDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RenameJobTemplateDto" /> class.
        /// </summary>
        /// <param name="newName">newName.</param>
        /// <param name="oldName">oldName.</param>
        public RenameJobTemplateDto(string newName = default(string), string oldName = default(string))
        {
            this.NewName = newName;
            this.OldName = oldName;
        }

        /// <summary>
        /// Gets or Sets NewName
        /// </summary>
        [DataMember(Name = "newName", EmitDefaultValue = true)]
        public string NewName { get; set; }

        /// <summary>
        /// Gets or Sets OldName
        /// </summary>
        [DataMember(Name = "oldName", EmitDefaultValue = true)]
        public string OldName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RenameJobTemplateDto {\n");
            sb.Append("  NewName: ").Append(NewName).Append("\n");
            sb.Append("  OldName: ").Append(OldName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RenameJobTemplateDto);
        }

        /// <summary>
        /// Returns true if RenameJobTemplateDto instances are equal
        /// </summary>
        /// <param name="input">Instance of RenameJobTemplateDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RenameJobTemplateDto input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.NewName == input.NewName ||
                    (this.NewName != null &&
                    this.NewName.Equals(input.NewName))
                ) && 
                (
                    this.OldName == input.OldName ||
                    (this.OldName != null &&
                    this.OldName.Equals(input.OldName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NewName != null)
                {
                    hashCode = (hashCode * 59) + this.NewName.GetHashCode();
                }
                if (this.OldName != null)
                {
                    hashCode = (hashCode * 59) + this.OldName.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
