/*
 * aida-mini
 *
 * 1.3.5-dev.2+010ffe2cb3fa5597fddacb6f4c0bef4aefc1e852
 *
 * The version of the OpenAPI document: 1.3.5-dev.2+010ffe2cb3fa5597fddacb6f4c0bef4aefc1e852
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Mini.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Mini.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Mini.Model
{
    /// <summary>
    /// Defines SecurityFeatureKind
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SecurityFeatureKind
    {
        /// <summary>
        /// Enum None for value: None
        /// </summary>
        [EnumMember(Value = "None")]
        None = 1,

        /// <summary>
        /// Enum Cli for value: Cli
        /// </summary>
        [EnumMember(Value = "Cli")]
        Cli = 2,

        /// <summary>
        /// Enum Mli for value: Mli
        /// </summary>
        [EnumMember(Value = "Mli")]
        Mli = 3

    }

}
